apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma-config
  labels:
    app: prisma
data:
  PRISMA_CONFIG: |
    port: 4466
    databases:
      default:
        connector: mysql
        host: mysql
        port: 3306
        user: root
        password: prisma
