apiVersion: v1
kind: ConfigMap
metadata:
  name: prisma-config
  labels:
    app: prisma
data:
    PRISMA_CONFIG: |
      port: 4466
      databases:
        default:
          connector: postgres
          host: postgres
          port: 5432
          user: prisma
          password: prisma